version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meeting_manager
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "main.py"]
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    restart: unless-stopped
